export const categories = [
  { id: 1,  name: "Rozwój osobisty",                slug: "rozwoj-osobisty",                icon: "🌱", count: 24 },
  { id: 2,  name: "Produktywność i efektywność",    slug: "produktywnosc-i-efektywnosc",    icon: "⚡", count: 23 },
  { id: 3,  name: "Komunikacja i relacje",          slug: "komunikacja-i-relacje",          icon: "💬", count: 11 },
  { id: 4,  name: "Pieniądze i wolność finansowa",  slug: "pieniadze-i-wolnosc-finansowa",  icon: "💰", count: 13 },
  { id: 5,  name: "Kariera i sukces",               slug: "kariera-i-sukces",               icon: "🏆", count: 12 },
  { id: 6,  name: "Przedsiębiorczość i start-up",   slug: "przedsiebiorczosc-i-start-up",   icon: "🚀", count: 21 },
  { id: 7,  name: "Marketing",                      slug: "marketing",                      icon: "📣", count: 14 },
  { id: 8,  name: "Biznes i przywództwo",           slug: "biznes-i-przywodztwo",           icon: "📊", count: 14 },
  { id: 9,  name: "Psychologia",                    slug: "psychologia",                    icon: "🧠", count: 13 },
  { id: 10, name: "Rozwój duchowy",                 slug: "rozwoj-duchowy",                 icon: "✨", count: 2  },
  { id: 11, name: "Zdrowie",                        slug: "zdrowie",                        icon: "💪", count: 2  },
];

export const allBooks = [
  {
    id: 1,
    title: "Jak zdobyć przyjaciół i zjednać sobie ludzi",
    author: "Dale Carnegie",
    rating: 4.7,
    reviewCount: 124,
    readTime: 37,
    category: "Komunikacja i relacje",
    categories: ["Komunikacja i relacje"],
    hasAudio: true,
    isFree: true,
    slug: "jak-zdobyc-przyjaciol",
    cover: "/covers/books/Jak zdobyć przyjaciół i zjednać sobie ludzi.png",
  },
  {
    id: 2,
    title: "Praca Głęboka",
    author: "Cal Newport",
    rating: 4.44,
    reviewCount: 56,
    readTime: 37,
    category: "Produktywność i efektywność",
    categories: ["Produktywność i efektywność"],
    hasAudio: true,
    isFree: false,
    slug: "praca-gleboka",
    cover: "/covers/books/Praca głęboka.png",
  },
  {
    id: 3,
    title: "Atomowe nawyki",
    author: "James Clear",
    rating: 4.82,
    reviewCount: 69,
    readTime: 31,
    category: "Produktywność i efektywność",
    categories: ["Produktywność i efektywność"],
    hasAudio: true,
    isFree: false,
    slug: "atomowe-nawyki",
    cover: "/covers/books/Atomowe nawyki.png",
  },
  {
    id: 4,
    title: "Otoczeni przez idiotów",
    author: "Thomas Erikson",
    rating: 4.0,
    reviewCount: 32,
    readTime: 18,
    category: "Komunikacja i relacje",
    categories: ["Komunikacja i relacje"],
    hasAudio: true,
    isFree: false,
    slug: "otoczeni-przez-idiotow",
    cover: "/covers/books/Otoczeni przez idiotów.png",
  },
  {
    id: 5,
    title: "Wywieranie wpływu na ludzi",
    author: "Robert Cialdini",
    rating: 4.69,
    reviewCount: 49,
    readTime: 31,
    category: "Komunikacja i relacje",
    categories: ["Komunikacja i relacje", "Psychologia"],
    hasAudio: true,
    isFree: false,
    slug: "wywieranie-wplywu-na-ludzi",
    cover: "/covers/books/Wywieranie wpływu na ludzi.png",
  },
  {
    id: 6,
    title: "Siła nawyku",
    author: "Charles Duhigg",
    rating: 4.78,
    reviewCount: 43,
    readTime: 30,
    category: "Produktywność i efektywność",
    categories: ["Produktywność i efektywność"],
    hasAudio: true,
    isFree: false,
    slug: "sila-nawyku",
    cover: "/covers/books/Siła nawyku.png",
  },
  {
    id: 7,
    title: "Potęga podświadomości",
    author: "Joseph Murphy",
    rating: 4.2,
    reviewCount: 35,
    readTime: 34,
    category: "Rozwój osobisty",
    categories: ["Rozwój osobisty"],
    hasAudio: true,
    isFree: false,
    slug: "potega-podswiadomosci",
    cover: "/covers/books/Potęga podświadomości.png",
  },
  {
    id: 8,
    title: "4-godzinny tydzień pracy",
    author: "Timothy Ferriss",
    rating: 4.9,
    reviewCount: 64,
    readTime: 36,
    category: "Przedsiębiorczość i start-up",
    categories: ["Przedsiębiorczość i start-up"],
    hasAudio: true,
    isFree: false,
    slug: "4-godzinny-tydzien-pracy",
    cover: "/covers/books/4-godzinny tydzień pracy.png",
  },
  {
    id: 9,
    title: "Potęga teraźniejszości",
    author: "Eckhart Tolle",
    rating: 4.4,
    reviewCount: 39,
    readTime: 30,
    category: "Rozwój osobisty",
    categories: ["Rozwój osobisty", "Rozwój duchowy"],
    hasAudio: true,
    isFree: false,
    slug: "potega-terazniejszosci",
    cover: "/covers/books/Potęga teraźniejszości.png",
  },
  {
    id: 10,
    title: "7 nawyków skutecznego działania",
    author: "Stephen Covey",
    rating: 4.5,
    reviewCount: 68,
    readTime: 29,
    category: "Rozwój osobisty",
    categories: ["Rozwój osobisty", "Produktywność i efektywność"],
    hasAudio: true,
    isFree: false,
    slug: "7-nawykow-skutecznego-dzialania",
    cover: "/covers/books/7 nawyków skutecznego działania.png",
  },
  {
    id: 11,
    title: "Bogaty ojciec, biedny ojciec",
    author: "Robert Kiyosaki",
    rating: 4.4,
    reviewCount: 64,
    readTime: 32,
    category: "Pieniądze i wolność finansowa",
    categories: ["Pieniądze i wolność finansowa"],
    hasAudio: true,
    isFree: false,
    slug: "bogaty-ojciec-biedny-ojciec",
    cover: "/covers/books/Biedny ojciec, bogaty ojciec.png",
  },
  {
    id: 12,
    title: "Obudź w sobie olbrzyma",
    author: "Anthony Robbins",
    rating: 4.7,
    reviewCount: 43,
    readTime: 38,
    category: "Rozwój osobisty",
    categories: ["Rozwój osobisty"],
    hasAudio: true,
    isFree: false,
    slug: "obudz-w-sobie-olbrzyma",
    cover: "/covers/books/Obudź w sobie olbrzyma.png",
  },
  {
    id: 13,
    title: "48 praw władzy",
    author: "Robert Greene",
    rating: 4.4,
    reviewCount: 58,
    readTime: 43,
    category: "Rozwój osobisty",
    categories: ["Rozwój osobisty"],
    hasAudio: true,
    isFree: false,
    slug: "48-praw-wladzy",
    cover: "/covers/books/48 praw władzy.png",
  },
  {
    id: 14,
    title: "Fenomen poranka",
    author: "Hal Elrod",
    rating: 4.22,
    reviewCount: 43,
    readTime: 27,
    category: "Produktywność i efektywność",
    categories: ["Produktywność i efektywność", "Rozwój osobisty"],
    hasAudio: true,
    isFree: false,
    slug: "fenomen-poranka",
    cover: "/covers/books/Fenomen poranka.png",
  },
  {
    id: 15,
    title: "Bogaty albo biedny",
    author: "T. Harv Eker",
    rating: 4.0,
    reviewCount: 36,
    readTime: 35,
    category: "Pieniądze i wolność finansowa",
    categories: ["Pieniądze i wolność finansowa"],
    hasAudio: true,
    isFree: false,
    slug: "bogaty-albo-biedny",
    cover: "/covers/books/Bogaty albo biedny.png",
  },
  {
    id: 16,
    title: "Jedna rzecz",
    author: "Gary Keller, Jay Papasan",
    rating: 4.6,
    reviewCount: 55,
    readTime: 32,
    category: "Produktywność i efektywność",
    categories: ["Produktywność i efektywność"],
    hasAudio: true,
    isFree: false,
    slug: "jedna-rzecz",
    cover: "/covers/books/Jedna rzecz.png",
  },
  {
    id: 17,
    title: "Jak przestać się martwić i zacząć żyć",
    author: "Dale Carnegie",
    rating: 4.4,
    reviewCount: 34,
    readTime: 36,
    category: "Rozwój osobisty",
    categories: ["Rozwój osobisty"],
    hasAudio: true,
    isFree: false,
    slug: "jak-przestac-sie-martwic-i-zaczac-zyc",
    cover: "/covers/books/Jak przestać się martwić i zacząć żyć.png",
  },
  {
    id: 18,
    title: "Inteligencja emocjonalna",
    author: "Daniel Goleman",
    rating: 4.7,
    reviewCount: 37,
    readTime: 40,
    category: "Komunikacja i relacje",
    categories: ["Komunikacja i relacje"],
    hasAudio: true,
    isFree: false,
    slug: "inteligencja-emocjonalna",
    cover: "/covers/books/Inteligencja emocjonalna.png",
  },
  {
    id: 19,
    title: "Subtelnie mówię F*ck",
    author: "Mark Manson",
    rating: 4.2,
    reviewCount: 48,
    readTime: 28,
    category: "Rozwój osobisty",
    categories: ["Rozwój osobisty"],
    hasAudio: true,
    isFree: false,
    slug: "subtelnie-mowie-fck",
    cover: "/covers/books/Subtelnie mówię fuck.png",
  },
  {
    id: 20,
    title: "Klub 5 rano",
    author: "Robin Sharma",
    rating: 4.4,
    reviewCount: 40,
    readTime: 30,
    category: "Produktywność i efektywność",
    categories: ["Produktywność i efektywność", "Rozwój osobisty"],
    hasAudio: true,
    isFree: false,
    slug: "klub-5-rano",
    cover: "/covers/books/Klub 5 rano.png",
  },
  {
    id: 21,
    title: "Kto zabrał mój ser?",
    author: "Spencer Johnson",
    rating: 4.31,
    reviewCount: 47,
    readTime: 19,
    category: "Rozwój osobisty",
    categories: ["Rozwój osobisty"],
    hasAudio: true,
    isFree: false,
    slug: "kto-zabral-moj-ser",
    cover: "/covers/books/Kto zabrał mój ser.png",
  },
  {
    id: 22,
    title: "12 życiowych zasad",
    author: "Jordan B. Peterson",
    rating: 4.42,
    reviewCount: 39,
    readTime: 43,
    category: "Rozwój osobisty",
    categories: ["Rozwój osobisty"],
    hasAudio: true,
    isFree: false,
    slug: "12-zyciowych-zasad",
    cover: "/covers/books/12 życiowych zasad.png",
  },
  {
    id: 23,
    title: "Rework",
    author: "Jason Fried, David Heinemeier Hansson",
    rating: 3.9,
    reviewCount: 49,
    readTime: 51,
    category: "Przedsiębiorczość i start-up",
    categories: ["Przedsiębiorczość i start-up"],
    hasAudio: true,
    isFree: false,
    slug: "rework",
    cover: "/covers/books/Rework.png",
  },
  {
    id: 24,
    title: "Niskobudżetowy startup",
    author: "Chris Guillebeau",
    rating: 4.6,
    reviewCount: 52,
    readTime: 31,
    category: "Przedsiębiorczość i start-up",
    categories: ["Przedsiębiorczość i start-up"],
    hasAudio: true,
    isFree: false,
    slug: "niskobudzetowy-startup",
    cover: "/covers/books/Niskobudżetowy startup.png",
  },
  {
    id: 25,
    title: "Zaczynaj od dlaczego",
    author: "Simon Sinek",
    rating: 4.0,
    reviewCount: 46,
    readTime: 20,
    category: "Przedsiębiorczość i start-up",
    categories: ["Przedsiębiorczość i start-up", "Kariera i sukces"],
    hasAudio: true,
    isFree: false,
    slug: "zaczynaj-od-dlaczego",
    cover: "/covers/books/Zaczynaj od dlaczego.png",
  },
  {
    id: 26,
    title: "Alchemik",
    author: "Paulo Coelho",
    rating: 4.3,
    reviewCount: 35,
    readTime: 21,
    category: "Rozwój duchowy",
    categories: ["Rozwój duchowy"],
    hasAudio: true,
    isFree: false,
    slug: "alchemik",
    cover: "/covers/books/Alchemik.png",
  },
  {
    id: 27,
    title: "8 nawyk. Od efektywności do wielkości",
    author: "Stephen Covey",
    rating: 3.8,
    reviewCount: 28,
    readTime: 28,
    category: "Biznes i przywództwo",
    categories: ["Biznes i przywództwo"],
    hasAudio: true,
    isFree: false,
    slug: "8-nawyk-od-efektywnosci-do-wielkosci",
    cover: "/covers/books/8. Nawyk.png",
  },
  {
    id: 28,
    title: "Negocjuj jakby od tego zależało twoje życie",
    author: "Chris Voss, Tahl Raz",
    rating: 4.9,
    reviewCount: 61,
    readTime: 82,
    category: "Kariera i sukces",
    categories: ["Kariera i sukces", "Komunikacja i relacje"],
    hasAudio: true,
    isFree: false,
    slug: "negocjuj-jakby-od-tego-zalezalo-twoje-zycie",
    cover: "/covers/books/Negocjuj jakby od tego zależało twoje życie.png",
  },
  {
    id: 29,
    title: "Jak stać się doskonałym mówcą i rozmówcą",
    author: "Dale Carnegie",
    rating: 4.1,
    reviewCount: 39,
    readTime: 34,
    category: "Komunikacja i relacje",
    categories: ["Komunikacja i relacje", "Kariera i sukces", "Biznes i przywództwo"],
    hasAudio: true,
    isFree: false,
    slug: "jak-stac-sie-doskonalym-mowca-i-rozmowca",
    cover: "/covers/books/Jak stać się doskonałym mówcą i rozmówcą.png",
  },
  {
    id: 30,
    title: "Zjedz tę żabę",
    author: "Brian Tracy",
    rating: 4.7,
    reviewCount: 54,
    readTime: 26,
    category: "Produktywność i efektywność",
    categories: ["Produktywność i efektywność"],
    hasAudio: true,
    isFree: false,
    slug: "zjedz-te-zabe",
    cover: "/covers/books/Zjedz tę żabę.png",
  },
  {
    id: 31,
    title: "Mądrzej, szybciej, lepiej",
    author: "Charles Duhigg",
    rating: 4.3,
    reviewCount: 44,
    readTime: 36,
    category: "Produktywność i efektywność",
    categories: ["Produktywność i efektywność"],
    hasAudio: true,
    isFree: false,
    slug: "madrzej-szybciej-lepiej",
    cover: "/covers/books/Mądrzej, szybciej, lepiej.png",
  },
  {
    id: 32,
    title: "Mikronawyki",
    author: "BJ Fogg",
    rating: 4.4,
    reviewCount: 38,
    readTime: 33,
    category: "Produktywność i efektywność",
    categories: ["Produktywność i efektywność"],
    hasAudio: true,
    isFree: false,
    slug: "mikronawyki",
    cover: "/covers/books/Mikronawyki.png",
  },
  {
    id: 33,
    title: "Reguła 80/20",
    author: "Richard Koch",
    rating: 3.8,
    reviewCount: 42,
    readTime: 31,
    category: "Produktywność i efektywność",
    categories: ["Produktywność i efektywność", "Biznes i przywództwo"],
    hasAudio: true,
    isFree: false,
    slug: "regula-8020",
    cover: "/covers/books/Reguła 80 20.png",
  },
  {
    id: 34,
    title: "Najpierw rzeczy najważniejsze",
    author: "Stephen R. Covey",
    rating: 4.2,
    reviewCount: 35,
    readTime: 29,
    category: "Produktywność i efektywność",
    categories: ["Produktywność i efektywność"],
    hasAudio: true,
    isFree: false,
    slug: "najpierw-rzeczy-najwazniejsze",
    cover: "/covers/books/Najpierw rzeczy najważniejsze.png",
  },
  {
    id: 35,
    title: "Getting Things Done",
    author: "David Allen",
    rating: 4.5,
    reviewCount: 36,
    readTime: 25,
    category: "Produktywność i efektywność",
    categories: ["Produktywność i efektywność"],
    hasAudio: true,
    isFree: false,
    slug: "getting-things-done",
    cover: "/covers/books/Getting Things Done.png",
  },
  {
    id: 36,
    title: "Najbogatszy człowiek w Babilonie",
    author: "George Samuel Clason",
    rating: 4.71,
    reviewCount: 41,
    readTime: 28,
    category: "Pieniądze i wolność finansowa",
    categories: ["Pieniądze i wolność finansowa"],
    hasAudio: true,
    isFree: false,
    slug: "najbogatszy-czlowiek-w-babilonie",
    cover: "/covers/books/Najbogatszy człowiek w Babilonie.png",
  },
  {
    id: 37,
    title: "Fastlane Milionera",
    author: "MJ DeMarco",
    rating: 4.9,
    reviewCount: 59,
    readTime: 46,
    category: "Pieniądze i wolność finansowa",
    categories: ["Pieniądze i wolność finansowa"],
    hasAudio: true,
    isFree: false,
    slug: "fastlane-milionera",
    cover: "/covers/books/Fastlane milionera.png",
  },
  {
    id: 38,
    title: "Psychologia pieniędzy",
    author: "Morgan Housel",
    rating: 4.6,
    reviewCount: 45,
    readTime: 37,
    category: "Pieniądze i wolność finansowa",
    categories: ["Pieniądze i wolność finansowa"],
    hasAudio: true,
    isFree: false,
    slug: "psychologia-pieniedzy",
    cover: "/covers/books/Psychologia pieniędzy.png",
  },
  {
    id: 39,
    title: "Myśl i bogać się",
    author: "Napoleon Hill",
    rating: 4.02,
    reviewCount: 65,
    readTime: 33,
    category: "Pieniądze i wolność finansowa",
    categories: ["Pieniądze i wolność finansowa"],
    hasAudio: true,
    isFree: false,
    slug: "mysl-i-bogac-sie",
    cover: "/covers/books/Myśl i bogać się.png",
  },
  {
    id: 40,
    title: "Strategia błękitnego oceanu",
    author: "W. Chan Kim, Renée Mauborgne",
    rating: 4.6,
    reviewCount: 62,
    readTime: 47,
    category: "Przedsiębiorczość i start-up",
    categories: ["Przedsiębiorczość i start-up", "Biznes i przywództwo"],
    hasAudio: true,
    isFree: false,
    slug: "strategia-blekitnego-oceanu",
    cover: "/covers/books/Strategia błękitnego oceanu.png",
  },
  {
    id: 41,
    title: "MIT przedsiębiorczości",
    author: "Michael E. Gerber",
    rating: 4.5,
    reviewCount: 54,
    readTime: 21,
    category: "Przedsiębiorczość i start-up",
    categories: ["Przedsiębiorczość i start-up"],
    hasAudio: true,
    isFree: false,
    slug: "mit-przedsiebiorczosci",
    cover: "/covers/books/Mit przedsiębiorczości.png",
  },
  {
    id: 42,
    title: "Metoda Lean Startup",
    author: "Eric Ries",
    rating: 4.8,
    reviewCount: 42,
    readTime: 29,
    category: "Przedsiębiorczość i start-up",
    categories: ["Przedsiębiorczość i start-up"],
    hasAudio: true,
    isFree: false,
    slug: "metoda-lean-startup",
    cover: "/covers/books/Metoda Lean Startup.png",
  },
  {
    id: 43,
    title: "Sztuka zwycięstwa",
    author: "Phil Knight",
    rating: 4.7,
    reviewCount: 49,
    readTime: 28,
    category: "Kariera i sukces",
    categories: ["Kariera i sukces", "Biznes i przywództwo", "Przedsiębiorczość i start-up"],
    hasAudio: true,
    isFree: false,
    slug: "sztuka-zwyciestwa",
    cover: "/covers/books/Sztuka zwycięstwa.png",
  },
  {
    id: 44,
    title: "Zero to One",
    author: "Peter Thiel",
    rating: 4.5,
    reviewCount: 58,
    readTime: 30,
    category: "Przedsiębiorczość i start-up",
    categories: ["Przedsiębiorczość i start-up"],
    hasAudio: true,
    isFree: false,
    slug: "zero-to-one",
    cover: "/covers/books/Zero to one.png",
  },
  {
    id: 45,
    title: "Cztery tysiące tygodni",
    author: "Oliver Burkeman",
    rating: 4.2,
    reviewCount: 41,
    readTime: 26,
    category: "Rozwój osobisty",
    categories: ["Rozwój osobisty", "Rozwój duchowy"],
    hasAudio: true,
    isFree: false,
    slug: "cztery-tysiace-tygodni",
    cover: "/covers/books/Cztery tysiące tygodni.png",
  },
  {
    id: 46,
    title: "Prawa ludzkiej natury",
    author: "Robert Greene",
    rating: 4.6,
    reviewCount: 31,
    readTime: 57,
    category: "Komunikacja i relacje",
    categories: ["Komunikacja i relacje"],
    hasAudio: true,
    isFree: false,
    slug: "prawa-ludzkiej-natury",
    cover: "/covers/books/Prawa ludzkiej natury.png",
  },
  {
    id: 47,
    title: "Poza porządek",
    author: "Jordan B. Peterson",
    rating: 4.42,
    reviewCount: 39,
    readTime: 29,
    category: "Rozwój osobisty",
    categories: ["Rozwój osobisty"],
    hasAudio: true,
    isFree: false,
    slug: "poza-porzadek",
    cover: "/covers/books/Poza porządek.png",
  },
  {
    id: 48,
    title: "Zbuduj swój drugi mózg",
    author: "Tiago Forte",
    rating: 4.6,
    reviewCount: 49,
    readTime: 29,
    category: "Produktywność i efektywność",
    categories: ["Produktywność i efektywność"],
    hasAudio: true,
    isFree: false,
    slug: "zbuduj-swoj-drugi-mozg",
    cover: "/covers/books/Zbuduj swój drugi mózg.png",
  },
  {
    id: 49,
    title: "Drive",
    author: "Daniel H. Pink",
    rating: 4.7,
    reviewCount: 53,
    readTime: 34,
    category: "Kariera i sukces",
    categories: ["Kariera i sukces", "Psychologia"],
    hasAudio: true,
    isFree: false,
    slug: "drive",
    cover: "/covers/books/Drive.png",
  },
  {
    id: 50,
    title: "Siła woli",
    author: "Kelly McGonigal",
    rating: 3.8,
    reviewCount: 36,
    readTime: 32,
    category: "Produktywność i efektywność",
    categories: ["Produktywność i efektywność"],
    hasAudio: true,
    isFree: false,
    slug: "sila-woli",
    cover: "/covers/books/Siła woli.png",
  },
  {
    id: 51,
    title: "Psycho-cybernetyka",
    author: "Maxwell Maltz",
    rating: 4.4,
    reviewCount: 48,
    readTime: 32,
    category: "Psychologia",
    categories: ["Psychologia", "Rozwój osobisty"],
    hasAudio: true,
    isFree: false,
    slug: "psycho-cybernetyka",
    cover: "/covers/books/Psycho-cybernetyka.png",
  },
  {
    id: 52,
    title: "Pułapki myślenia",
    author: "Daniel Kahneman",
    rating: 4.8,
    reviewCount: 63,
    readTime: 35,
    category: "Psychologia",
    categories: ["Psychologia"],
    hasAudio: true,
    isFree: false,
    slug: "pulapki-myslenia",
    cover: "/covers/books/Pułapki myślenia.png",
  },
  {
    id: 53,
    title: "Metoda Running Lean",
    author: "Ash Maurya",
    rating: 3.9,
    reviewCount: 37,
    readTime: 28,
    category: "Przedsiębiorczość i start-up",
    categories: ["Przedsiębiorczość i start-up"],
    hasAudio: true,
    isFree: false,
    slug: "metoda-running-lean",
    cover: "/covers/books/Metoda Running Lean.png",
  },
  {
    id: 54,
    title: "Tworzenie modeli biznesowych",
    author: "Alexander Osterwalder, Yves Pigneur",
    rating: 4.5,
    reviewCount: 55,
    readTime: 33,
    category: "Przedsiębiorczość i start-up",
    categories: ["Przedsiębiorczość i start-up"],
    hasAudio: true,
    isFree: false,
    slug: "tworzenie-modeli-biznesowych",
    cover: "/covers/books/Tworzenie modeli biznesowych.png",
  },
  {
    id: 55,
    title: "Trakcja, czyli jak zdobyć pierwszych klientów",
    author: "Gabriel Weinberg, Justin Mares",
    rating: 4.3,
    reviewCount: 30,
    readTime: 40,
    category: "Marketing",
    categories: ["Marketing"],
    hasAudio: true,
    isFree: false,
    slug: "trakcja-czyli-jak-zdobyc-pierwszych-klientow",
    cover: "/covers/books/Trakcja, czyli złap przyczepność.png",
  },
  {
    id: 56,
    title: "Tajemnice skutecznych dotcomów",
    author: "Russell Brunson",
    rating: 4.6,
    reviewCount: 53,
    readTime: 21,
    category: "Przedsiębiorczość i start-up",
    categories: ["Przedsiębiorczość i start-up", "Marketing"],
    hasAudio: true,
    isFree: false,
    slug: "tajemnice-skutecznych-dotcomow",
    cover: "/covers/books/Tajniki skutecznych dotcomów.png",
  },
  {
    id: 57,
    title: "Firma, czyli Ty",
    author: "Paul Jarvis",
    rating: 4.4,
    reviewCount: 40,
    readTime: 25,
    category: "Przedsiębiorczość i start-up",
    categories: ["Przedsiębiorczość i start-up"],
    hasAudio: true,
    isFree: false,
    slug: "firma-czyli-ty",
    cover: "/covers/books/Firma czyli Ty.png",
  },
  {
    id: 58,
    title: "Pięciodniowy sprint",
    author: "Jake Knapp, John Zeratsky, Braden Kowitz",
    rating: 4.1,
    reviewCount: 32,
    readTime: 31,
    category: "Przedsiębiorczość i start-up",
    categories: ["Przedsiębiorczość i start-up"],
    hasAudio: true,
    isFree: false,
    slug: "pieciodniowy-sprint",
    cover: "/covers/books/Pięciodniowy sprint.png",
  },
  {
    id: 59,
    title: "Przyczepne historie",
    author: "Chip Heath, Dan Heath",
    rating: 4.59,
    reviewCount: 44,
    readTime: 15,
    category: "Marketing",
    categories: ["Marketing"],
    hasAudio: true,
    isFree: false,
    slug: "przyczepne-historie",
    cover: "/covers/books/Przyczepne historie.png",
  },
  {
    id: 60,
    title: "Plan marketingowy na jednej stronie",
    author: "Allan Dib",
    rating: 4.0,
    reviewCount: 36,
    readTime: 21,
    category: "Przedsiębiorczość i start-up",
    categories: ["Przedsiębiorczość i start-up", "Marketing"],
    hasAudio: true,
    isFree: false,
    slug: "plan-marketingowy-na-jednej-stronie",
    cover: "/covers/books/Plan marketingowy na jednej stronie.png",
  },
  {
    id: 61,
    title: "Fioletowa krowa",
    author: "Seth Godin",
    rating: 4.3,
    reviewCount: 46,
    readTime: 17,
    category: "Marketing",
    categories: ["Marketing"],
    hasAudio: true,
    isFree: false,
    slug: "fioletowa-krowa",
    cover: "/covers/books/Fioletowa krowa.png",
  },
  {
    id: 62,
    title: "Skuszeni",
    author: "Nir Eyal, Ryan Hoover",
    rating: 4.2,
    reviewCount: 38,
    readTime: 32,
    category: "Marketing",
    categories: ["Marketing"],
    hasAudio: true,
    isFree: false,
    slug: "skuszeni",
    cover: "/covers/books/Skuszeni.png",
  },
  {
    id: 63,
    title: "Efekt viralowy",
    author: "Jonah Berger",
    rating: 4.5,
    reviewCount: 51,
    readTime: 30,
    category: "Marketing",
    categories: ["Marketing"],
    hasAudio: true,
    isFree: false,
    slug: "efekt-viralowy",
    cover: "/covers/books/Efekt viralowy.png",
  },
  {
    id: 64,
    title: "Jak zostać mistrzem",
    author: "Robert Greene",
    rating: 4.7,
    reviewCount: 58,
    readTime: 45,
    category: "Kariera i sukces",
    categories: ["Kariera i sukces"],
    hasAudio: true,
    isFree: false,
    slug: "jak-zostac-mistrzem",
    cover: "/covers/books/Jak zostać mistrzem.png",
  },
  {
    id: 65,
    title: "Nowa psychologia sukcesu",
    author: "Carol Dweck",
    rating: 4.8,
    reviewCount: 32,
    readTime: 25,
    category: "Rozwój osobisty",
    categories: ["Rozwój osobisty", "Psychologia"],
    hasAudio: true,
    isFree: false,
    slug: "nowa-psychologia-sukcesu",
    cover: "/covers/books/Nowa psychologia sukcesu.png",
  },
  {
    id: 66,
    title: "Liderzy jedzą na końcu",
    author: "Simon Sinek",
    rating: 3.9,
    reviewCount: 34,
    readTime: 31,
    category: "Biznes i przywództwo",
    categories: ["Biznes i przywództwo"],
    hasAudio: true,
    isFree: false,
    slug: "liderzy-jedza-na-koncu",
    cover: "/covers/books/Liderzy jedzą na końcu.png",
  },
  {
    id: 67,
    title: "Nowy jednominutowy menedżer",
    author: "Ken Blanchard, Spencer Johnson",
    rating: 4.3,
    reviewCount: 49,
    readTime: 23,
    category: "Biznes i przywództwo",
    categories: ["Biznes i przywództwo"],
    hasAudio: true,
    isFree: false,
    slug: "nowy-jednominutowy-menedzer",
    cover: "/covers/books/Jednominutowy menedżer.png",
  },
  {
    id: 68,
    title: "Gra bez końca",
    author: "Simon Sinek",
    rating: 4.2,
    reviewCount: 44,
    readTime: 47,
    category: "Biznes i przywództwo",
    categories: ["Biznes i przywództwo"],
    hasAudio: true,
    isFree: false,
    slug: "gra-bez-konca",
    cover: "/covers/books/Gra bez końca.png",
  },
  {
    id: 69,
    title: "Zasady",
    author: "Ray Dalio",
    rating: 4.1,
    reviewCount: 48,
    readTime: 24,
    category: "Biznes i przywództwo",
    categories: ["Biznes i przywództwo"],
    hasAudio: true,
    isFree: false,
    slug: "zasady",
    cover: "/covers/books/Zasady.png",
  },
  {
    id: 70,
    title: "Odwaga bycia nielubianym",
    author: "Ichiro Kishimi, Fumitake Koga",
    rating: 4.0,
    reviewCount: 31,
    readTime: 26,
    category: "Rozwój osobisty",
    categories: ["Rozwój osobisty"],
    hasAudio: true,
    isFree: false,
    slug: "odwaga-bycia-nielubianym",
    cover: "/covers/books/Odwaga bycia nielubianym.png",
  },
  {
    id: 71,
    title: "Dołek",
    author: "Seth Godin",
    rating: 4.4,
    reviewCount: 52,
    readTime: 16,
    category: "Przedsiębiorczość i start-up",
    categories: ["Przedsiębiorczość i start-up"],
    hasAudio: true,
    isFree: false,
    slug: "dolek",
    cover: "/covers/books/Dołek.png",
  },
  {
    id: 72,
    title: "Model StoryBrand",
    author: "Donald Miller",
    rating: 4.7,
    reviewCount: 34,
    readTime: 35,
    category: "Marketing",
    categories: ["Marketing"],
    hasAudio: true,
    isFree: false,
    slug: "model-storybrand",
    cover: "/covers/books/Model StoryBrand.png",
  },
  {
    id: 73,
    title: "Potęga irracjonalności",
    author: "Dan Ariely",
    rating: 4.6,
    reviewCount: 37,
    readTime: 32,
    category: "Psychologia",
    categories: ["Psychologia"],
    hasAudio: true,
    isFree: false,
    slug: "potega-irracjonalnosci",
    cover: "/covers/books/Potęga irracjonalności.png",
  },
  {
    id: 74,
    title: "Czarny łabędź",
    author: "Nassim Nicholas Taleb",
    rating: 4.9,
    reviewCount: 70,
    readTime: 26,
    category: "Psychologia",
    categories: ["Psychologia", "Rozwój osobisty"],
    hasAudio: true,
    isFree: false,
    slug: "czarny-labedz",
    cover: "/covers/books/Czarny łabęź.png",
  },
  {
    id: 75,
    title: "Niewolnicy dopaminy",
    author: "Anna Lembke",
    rating: 4.23,
    reviewCount: 29,
    readTime: 31,
    category: "Rozwój osobisty",
    categories: ["Rozwój osobisty"],
    hasAudio: true,
    isFree: false,
    slug: "niewolnicy-dopaminy",
    cover: "/covers/books/Niewolnicy dopaminy.png",
  },
  {
    id: 76,
    title: "Oddech",
    author: "James Nestor",
    rating: 4.5,
    reviewCount: 31,
    readTime: 34,
    category: "Zdrowie",
    categories: ["Zdrowie"],
    hasAudio: true,
    isFree: false,
    slug: "oddech",
    cover: "/covers/books/Oddech.png",
  },
  {
    id: 77,
    title: "W ogóle mnie nie słuchasz",
    author: "Kate Murphy",
    rating: 4.3,
    reviewCount: 33,
    readTime: 26,
    category: "Komunikacja i relacje",
    categories: ["Komunikacja i relacje"],
    hasAudio: true,
    isFree: false,
    slug: "w-ogole-mnie-nie-sluchasz",
    cover: "/covers/books/W ogóle mnie nie słuchasz.png",
  },
  {
    id: 78,
    title: "Sztuka uwodzenia",
    author: "Robert Greene",
    rating: 4.1,
    reviewCount: 41,
    readTime: 33,
    category: "Komunikacja i relacje",
    categories: ["Komunikacja i relacje"],
    hasAudio: true,
    isFree: false,
    slug: "sztuka-uwodzenia",
    cover: "/covers/books/Sztuka uwodzenia.png",
  },
  {
    id: 79,
    title: "Pre-swazja",
    author: "Robert Cialdini",
    rating: 4.6,
    reviewCount: 35,
    readTime: 31,
    category: "Komunikacja i relacje",
    categories: ["Komunikacja i relacje", "Psychologia"],
    hasAudio: true,
    isFree: false,
    slug: "pre-swazja",
    cover: "/covers/books/Pre-swazja.png",
  },
  {
    id: 80,
    title: "Kwadrant przepływu pieniędzy",
    author: "Robert Kiyosaki",
    rating: 3.9,
    reviewCount: 29,
    readTime: 22,
    category: "Pieniądze i wolność finansowa",
    categories: ["Pieniądze i wolność finansowa"],
    hasAudio: true,
    isFree: false,
    slug: "kwadrant-przeplywu-pieniedzy",
    cover: "/covers/books/Kwadrant przepływu pieniędzy.png",
  },
  {
    id: 81,
    title: "Nawyk samodyscypliny",
    author: "Neil Fiore",
    rating: 4.3,
    reviewCount: 42,
    readTime: 24,
    category: "Produktywność i efektywność",
    categories: ["Produktywność i efektywność"],
    hasAudio: true,
    isFree: false,
    slug: "nawyk-samodyscypliny",
    cover: "/covers/books/Nawyk samodyscypliny.png",
  },
  {
    id: 82,
    title: "Nic mnie nie złamie",
    author: "David Goggins",
    rating: 4.9,
    reviewCount: 59,
    readTime: 21,
    category: "Rozwój osobisty",
    categories: ["Rozwój osobisty"],
    hasAudio: true,
    isFree: false,
    slug: "nic-mnie-nie-zlamie",
    cover: "/covers/books/Nic mnie nie złamie.png",
  },
  {
    id: 83,
    title: "Przeskoczyć przepaść",
    author: "Geoffrey A. Moore",
    rating: 4.08,
    reviewCount: 32,
    readTime: 23,
    category: "Marketing",
    categories: ["Marketing"],
    hasAudio: true,
    isFree: false,
    slug: "przeskoczyc-przepasc",
    cover: "/covers/books/Przeskoczyć przepaść.png",
  },
  {
    id: 84,
    title: "Esencjalista",
    author: "Greg McKeown",
    rating: 4.68,
    reviewCount: 43,
    readTime: 30,
    category: "Produktywność i efektywność",
    categories: ["Produktywność i efektywność"],
    hasAudio: true,
    isFree: false,
    slug: "esencjalista",
    cover: "/covers/books/Esencjalista.png",
  },
  {
    id: 85,
    title: "Cyfrowy minimalizm",
    author: "Cal Newport",
    rating: 4.4,
    reviewCount: 36,
    readTime: 32,
    category: "Produktywność i efektywność",
    categories: ["Produktywność i efektywność"],
    hasAudio: true,
    isFree: false,
    slug: "cyfrowy-minimalizm",
    cover: "/covers/books/Cyfrowy minimalizm.png",
  },
  {
    id: 86,
    title: "To jest marketing",
    author: "Seth Godin",
    rating: 4.21,
    reviewCount: 62,
    readTime: 24,
    category: "Marketing",
    categories: ["Marketing"],
    hasAudio: true,
    isFree: false,
    slug: "to-jest-marketing",
    cover: "/covers/books/To jest marketing!.png",
  },
  {
    id: 87,
    title: "Zacznij myśleć jak mnich",
    author: "Jay Shetty",
    rating: 4.3,
    reviewCount: 36,
    readTime: 25,
    category: "Rozwój osobisty",
    categories: ["Rozwój osobisty"],
    hasAudio: true,
    isFree: false,
    slug: "zacznij-myslec-jak-mnich",
    cover: "/covers/books/Zacznij myśleć jak mnich.png",
  },
  {
    id: 88,
    title: "Nie każ mi myśleć",
    author: "Steve Krug",
    rating: 4.7,
    reviewCount: 29,
    readTime: 29,
    category: "Marketing",
    categories: ["Marketing", "Przedsiębiorczość i start-up"],
    hasAudio: true,
    isFree: false,
    slug: "nie-kaz-mi-myslec",
    cover: "/covers/books/Nie każ mi myśleć!.png",
  },
  {
    id: 89,
    title: "Dawaj innym szczęście",
    author: "Tony Hsieh",
    rating: 4.6,
    reviewCount: 33,
    readTime: 36,
    category: "Biznes i przywództwo",
    categories: ["Biznes i przywództwo", "Rozwój osobisty"],
    hasAudio: true,
    isFree: false,
    slug: "dawaj-innym-szczescie",
    cover: "/covers/books/Dawaj innym szczęście.png",
  },
  {
    id: 90,
    title: "Standard Bitcoina",
    author: "Saifedean Ammous",
    rating: 4.8,
    reviewCount: 53,
    readTime: 30,
    category: "Pieniądze i wolność finansowa",
    categories: ["Pieniądze i wolność finansowa"],
    hasAudio: true,
    isFree: false,
    slug: "standard-bitcoina",
    cover: "/covers/books/Standard Bitcoina.png",
  },
  {
    id: 91,
    title: "Almanach Navala Ravikanta",
    author: "Eric Jorgenson",
    rating: 4.32,
    reviewCount: 36,
    readTime: 31,
    category: "Pieniądze i wolność finansowa",
    categories: ["Pieniądze i wolność finansowa"],
    hasAudio: true,
    isFree: false,
    slug: "almanach-navala-ravikanta",
    cover: "/covers/books/Almanach Navala Ravikanta.png",
  },
  {
    id: 92,
    title: "Antykruchość",
    author: "Nassim Nicholas Taleb",
    rating: 4.5,
    reviewCount: 38,
    readTime: 31,
    category: "Psychologia",
    categories: ["Psychologia", "Rozwój osobisty"],
    hasAudio: true,
    isFree: false,
    slug: "antykruchosc",
    cover: "/covers/books/Antykruchość.png",
  },
  {
    id: 93,
    title: "Reguła 10X",
    author: "Grant Cardone",
    rating: 4.7,
    reviewCount: 42,
    readTime: 34,
    category: "Kariera i sukces",
    categories: ["Kariera i sukces", "Biznes i przywództwo"],
    hasAudio: true,
    isFree: false,
    slug: "regula-10x",
    cover: "/covers/books/Reguła 10X.png",
  },
  {
    id: 94,
    title: "Zwiedzeni przez przypadek",
    author: "Nassim Nicholas Taleb",
    rating: 4.4,
    reviewCount: 45,
    readTime: 28,
    category: "Psychologia",
    categories: ["Psychologia", "Rozwój osobisty"],
    hasAudio: true,
    isFree: false,
    slug: "zwiedzeni-przez-przypadek",
    cover: "/covers/books/Zwiedzeni przez przypadek.png",
  },
  {
    id: 95,
    title: "Gdy regułą jest brak reguł",
    author: "Reed Hastings, Erin Meyer",
    rating: 4.1,
    reviewCount: 30,
    readTime: 26,
    category: "Biznes i przywództwo",
    categories: ["Biznes i przywództwo"],
    hasAudio: true,
    isFree: false,
    slug: "gdy-regula-jest-brak-regul",
    cover: "/covers/books/Gdy regułą jest brak reguł.png",
  },
  {
    id: 96,
    title: "Mapy sensu",
    author: "Jordan B. Peterson",
    rating: 4.19,
    reviewCount: 37,
    readTime: 31,
    category: "Rozwój duchowy",
    categories: ["Rozwój duchowy", "Rozwój osobisty"],
    hasAudio: true,
    isFree: false,
    slug: "mapy-sensu",
    cover: "/covers/books/Mapy sensu.png",
  },
  {
    id: 97,
    title: "Ego to twój wróg",
    author: "Ryan Holiday",
    rating: 4.8,
    reviewCount: 47,
    readTime: 32,
    category: "Rozwój osobisty",
    categories: ["Rozwój osobisty", "Rozwój duchowy"],
    hasAudio: true,
    isFree: false,
    slug: "ego-to-twoj-wrog",
    cover: "/covers/books/Ego to twój wróg.png",
  },
  {
    id: 98,
    title: "Poza schematem",
    author: "Malcolm Gladwell",
    rating: 4.7,
    reviewCount: 35,
    readTime: 29,
    category: "Rozwój osobisty",
    categories: ["Rozwój osobisty", "Psychologia"],
    hasAudio: true,
    isFree: false,
    slug: "poza-schematem",
    cover: "/covers/books/Poza schematem.png",
  },
  {
    id: 99,
    title: "Od dobrego do wielkiego",
    author: "Jim Collins",
    rating: 4.2,
    reviewCount: 41,
    readTime: 29,
    category: "Biznes i przywództwo",
    categories: ["Biznes i przywództwo"],
    hasAudio: true,
    isFree: false,
    slug: "od-dobrego-do-wielkiego",
    cover: "/covers/books/Od dobrego do wielkiego.png",
  },
  {
    id: 100,
    title: "Unscripted",
    author: "MJ DeMarco",
    rating: 4.8,
    reviewCount: 41,
    readTime: 64,
    category: "Pieniądze i wolność finansowa",
    categories: ["Pieniądze i wolność finansowa", "Kariera i sukces"],
    hasAudio: true,
    isFree: false,
    slug: "unscripted",
    cover: "/covers/books/Unscripted.png",
  },
  {
    id: 101,
    title: "Od Z do A",
    author: "Colin Bryar, Bill Carr",
    rating: 4.6,
    reviewCount: 39,
    readTime: 24,
    category: "Biznes i przywództwo",
    categories: ["Biznes i przywództwo"],
    hasAudio: true,
    isFree: false,
    slug: "od-z-do-a",
    cover: "/covers/books/Od Z do A.png",
  },
  {
    id: 102,
    title: "Scrum",
    author: "Jeff Sutherland",
    rating: 4.6,
    reviewCount: 66,
    readTime: 34,
    category: "Przedsiębiorczość i start-up",
    categories: ["Przedsiębiorczość i start-up", "Produktywność i efektywność"],
    hasAudio: true,
    isFree: false,
    slug: "scrum",
    cover: "/covers/books/Scrum.png",
  },
  {
    id: 103,
    title: "Leniwy umysł",
    author: "Adam Grant",
    rating: 4.4,
    reviewCount: 39,
    readTime: 30,
    category: "Rozwój osobisty",
    categories: ["Rozwój osobisty", "Psychologia"],
    hasAudio: true,
    isFree: false,
    slug: "leniwy-umysl",
    cover: "/covers/books/Leniwy umysł.png",
  },
  {
    id: 104,
    title: "Metoda czarnej skrzynki",
    author: "Matthew Syed",
    rating: 4.8,
    reviewCount: 49,
    readTime: 30,
    category: "Psychologia",
    categories: ["Psychologia", "Rozwój osobisty"],
    hasAudio: true,
    isFree: false,
    slug: "metoda-czarnej-skrzynki",
    cover: "/covers/books/Metoda czarnej skrzynki.png",
  },
  {
    id: 105,
    title: "Paradoks wyboru",
    author: "Barry Schwartz",
    rating: 4.0,
    reviewCount: 37,
    readTime: 21,
    category: "Psychologia",
    categories: ["Psychologia"],
    hasAudio: true,
    isFree: false,
    slug: "paradoks-wyboru",
    cover: "/covers/books/Paradoks wyboru.png",
  },
  {
    id: 106,
    title: "Scaling Up",
    author: "Verne Harnish",
    rating: 4.7,
    reviewCount: 48,
    readTime: 35,
    category: "Przedsiębiorczość i start-up",
    categories: ["Przedsiębiorczość i start-up", "Biznes i przywództwo"],
    hasAudio: true,
    isFree: false,
    slug: "scaling-up",
    cover: "/covers/books/Scaling up.png",
  },
  {
    id: 107,
    title: "Sekrety amerykańskich milionerów",
    author: "Thomas J. Stanley, William D. Danko",
    rating: 4.13,
    reviewCount: 36,
    readTime: 36,
    category: "Pieniądze i wolność finansowa",
    categories: ["Pieniądze i wolność finansowa"],
    hasAudio: true,
    isFree: false,
    slug: "sekrety-amerykanskich-milionerow",
    cover: "/covers/books/Sekrety Amerykańskich milionerów.png",
  },
  {
    id: 108,
    title: "Błysk!",
    author: "Malcolm Gladwell",
    rating: 4.5,
    reviewCount: 46,
    readTime: 23,
    category: "Psychologia",
    categories: ["Psychologia"],
    hasAudio: true,
    isFree: false,
    slug: "blysk",
    cover: "/covers/books/Błysk!.png",
  },
  {
    id: 109,
    title: "Pstryk",
    author: "Chip Heath, Dan Heath",
    rating: 4.0,
    reviewCount: 36,
    readTime: 20,
    category: "Psychologia",
    categories: ["Psychologia"],
    hasAudio: true,
    isFree: false,
    slug: "pstryk",
    cover: "/covers/books/Pstryk.png",
  },
  {
    id: 110,
    title: "Ekstremalne przywództwo",
    author: "Jocko Willink, Leif Babin",
    rating: 4.3,
    reviewCount: 39,
    readTime: 31,
    category: "Biznes i przywództwo",
    categories: ["Biznes i przywództwo"],
    hasAudio: true,
    isFree: false,
    slug: "ekstremalne-przywodztwo",
    cover: "/covers/books/Ekstremalne przywództwo.png",
  },
  {
    id: 111,
    title: "Przeszkoda czy wyzwanie?",
    author: "Ryan Holiday",
    rating: 4.0,
    reviewCount: 32,
    readTime: 33,
    category: "Rozwój osobisty",
    categories: ["Rozwój osobisty", "Rozwój duchowy"],
    hasAudio: true,
    isFree: false,
    slug: "przeszkoda-czy-wyzwanie",
    cover: "/covers/books/Przeszkoda czy wyzwanie.png",
  },
  {
    id: 112,
    title: "Magia myślenia na wielką skalę",
    author: "David J. Schwartz",
    rating: 4.6,
    reviewCount: 45,
    readTime: 36,
    category: "Rozwój osobisty",
    categories: ["Rozwój osobisty"],
    hasAudio: true,
    isFree: false,
    slug: "magia-myslenia-na-wielka-skale",
    cover: "/covers/books/Magia myślenia na wielką skalę.png",
  },
  {
    id: 113,
    title: "Szef wymagający i wyrozumiały",
    author: "Kim Scott",
    rating: 4.5,
    reviewCount: 37,
    readTime: 30,
    category: "Biznes i przywództwo",
    categories: ["Biznes i przywództwo"],
    hasAudio: true,
    isFree: false,
    slug: "szef-wymagajacy-i-wyrozumialy",
    cover: "/covers/books/Szef wymagający i wyrozumiały.png",
  },
  {
    id: 114,
    title: "Punkty przełomowe",
    author: "Malcolm Gladwell",
    rating: 4.4,
    reviewCount: 41,
    readTime: 16,
    category: "Marketing",
    categories: ["Marketing", "Psychologia"],
    hasAudio: true,
    isFree: false,
    slug: "punkty-przelomowe",
    cover: "/covers/books/Punkt przełomowy.png",
  },
  {
    id: 115,
    title: "Narzędzia tytanów",
    author: "Timothy Ferriss",
    rating: 4.1,
    reviewCount: 32,
    readTime: 39,
    category: "Kariera i sukces",
    categories: ["Kariera i sukces"],
    hasAudio: true,
    isFree: false,
    slug: "narzedzia-tytanow",
    cover: "/covers/books/Narzędzia tytanów.png",
  },
  {
    id: 116,
    title: "Inteligentny inwestor",
    author: "Benjamin Graham",
    rating: 4.7,
    reviewCount: 44,
    readTime: 36,
    category: "Pieniądze i wolność finansowa",
    categories: ["Pieniądze i wolność finansowa"],
    hasAudio: true,
    isFree: false,
    slug: "inteligentny-inwestor",
    cover: "/covers/books/Inteligentny inwestor.png",
  },
  {
    id: 117,
    title: "Najtrudniejsze w tym, co trudne",
    author: "Ben Horowitz",
    rating: 4.8,
    reviewCount: 43,
    readTime: 35,
    category: "Biznes i przywództwo",
    categories: ["Biznes i przywództwo"],
    hasAudio: true,
    isFree: false,
    slug: "najtrudniejsze-w-tym-co-trudne",
    cover: "/covers/books/Najtrudniejsze w tym, co trudne.png",
  },
  {
    id: 118,
    title: "12 tygodniowy rok",
    author: "Brian P. Moran, Michael Lennington",
    rating: 4.3,
    reviewCount: 36,
    readTime: 31,
    category: "Produktywność i efektywność",
    categories: ["Produktywność i efektywność", "Biznes i przywództwo"],
    hasAudio: true,
    isFree: false,
    slug: "12-tygodniowy-rok",
    cover: "/covers/books/12 tygodniowy rok.png",
  },
  {
    id: 119,
    title: "Droga na szczyt",
    author: "Anders Ericsson, Robert Pool",
    rating: 4.6,
    reviewCount: 38,
    readTime: 28,
    category: "Kariera i sukces",
    categories: ["Kariera i sukces", "Produktywność i efektywność"],
    hasAudio: true,
    isFree: false,
    slug: "droga-na-szczyt",
    cover: "/covers/books/Droga na szczyt.png",
  },
  {
    id: 120,
    title: "Reguła 5 sekund",
    author: "Mel Robbins",
    rating: 3.9,
    reviewCount: 30,
    readTime: 28,
    category: "Produktywność i efektywność",
    categories: ["Produktywność i efektywność", "Kariera i sukces"],
    hasAudio: true,
    isFree: false,
    slug: "regula-5-sekund",
    cover: "/covers/books/Reguła 5 sekund.png",
  },
  {
    id: 121,
    title: "Like a Virgin",
    author: "Richard Branson",
    rating: 4.5,
    reviewCount: 48,
    readTime: 23,
    category: "Kariera i sukces",
    categories: ["Kariera i sukces"],
    hasAudio: true,
    isFree: false,
    slug: "like-a-virgin",
    cover: "/covers/books/Like a virgin.png",
  },
  {
    id: 122,
    title: "Wielka czwórka",
    author: "Scott Galloway",
    rating: 4.2,
    reviewCount: 42,
    readTime: 37,
    category: "Kariera i sukces",
    categories: ["Kariera i sukces"],
    hasAudio: true,
    isFree: false,
    slug: "wielka-czworka",
    cover: "/covers/books/Wielka czwórka.png",
  },
  {
    id: 123,
    title: "22 niezmienne prawa marketingu",
    author: "Al Ries, Jack Trout",
    rating: 4.0,
    reviewCount: 37,
    readTime: 35,
    category: "Marketing",
    categories: ["Marketing"],
    hasAudio: true,
    isFree: false,
    slug: "22-niezmienne-prawa-marketingu",
    cover: "/covers/books/22 Niezmienne prawa marketingu.png",
  },
  {
    id: 124,
    title: "Zdobyć rynek",
    author: "Jeff Walker",
    rating: 4.8,
    reviewCount: 44,
    readTime: 34,
    category: "Marketing",
    categories: ["Marketing"],
    hasAudio: true,
    isFree: false,
    slug: "zdobyc-rynek",
    cover: "/covers/books/Zdobyć rynek.png",
  },
  {
    id: 125,
    title: "Freakonomia",
    author: "Steven D. Levitt, Stephen J. Dubner",
    rating: 4.1,
    reviewCount: 46,
    readTime: 30,
    category: "Psychologia",
    categories: ["Psychologia"],
    hasAudio: true,
    isFree: false,
    slug: "freakonomia",
    cover: "/covers/books/Freakonomia.png",
  },
  {
    id: 126,
    title: "Kreatywność S.A.",
    author: "Ed Catmull",
    rating: 4.3,
    reviewCount: 38,
    readTime: 30,
    category: "Biznes i przywództwo",
    categories: ["Biznes i przywództwo"],
    hasAudio: true,
    isFree: false,
    slug: "kreatywnosc-sa",
    cover: "/covers/books/Kreatywność S. A..png",
  },
  {
    id: 127,
    title: "Zostań ultrasamoukiem",
    author: "Scott H. Young",
    rating: 4.71,
    reviewCount: 63,
    readTime: 45,
    category: "Produktywność i efektywność",
    categories: ["Produktywność i efektywność"],
    hasAudio: true,
    isFree: false,
    slug: "zostan-ultrasamoukiem",
    cover: "/covers/books/Zostań ultrasamoukiem.png",
  },
  {
    id: 128,
    title: "Tajniki zwiększania ruchu",
    author: "Russell Brunson",
    rating: 4.4,
    reviewCount: 41,
    readTime: 18,
    category: "Przedsiębiorczość i start-up",
    categories: ["Przedsiębiorczość i start-up", "Marketing"],
    hasAudio: true,
    isFree: false,
    slug: "tajniki-zwiekszania-ruchu",
    cover: "/covers/books/Tajniki zwiększania ruchu.png",
  },
  {
    id: 129,
    title: "Nigdy więcej nie trać klienta",
    author: "Joey Coleman",
    rating: 4.8,
    reviewCount: 35,
    readTime: 37,
    category: "Marketing",
    categories: ["Marketing"],
    hasAudio: true,
    isFree: false,
    slug: "nigdy-wiecej-nie-trac-klienta",
    cover: "/covers/books/Nigdy więcej nie trać Klienta.png",
  },
  {
    id: 130,
    title: "Ciszej proszę…",
    author: "Susan Cain",
    rating: 4.3,
    reviewCount: 42,
    readTime: 43,
    category: "Komunikacja i relacje",
    categories: ["Komunikacja i relacje"],
    hasAudio: true,
    isFree: false,
    slug: "ciszej-prosze",
    cover: "/covers/books/Ciszej proszę....png",
  },
  {
    id: 131,
    title: "Upór",
    author: "Angela Duckworth",
    rating: 4.6,
    reviewCount: 40,
    readTime: 39,
    category: "Kariera i sukces",
    categories: ["Kariera i sukces", "Rozwój osobisty"],
    hasAudio: true,
    isFree: false,
    slug: "upor",
    cover: "/covers/books/Upór.png",
  },
  {
    id: 132,
    title: "Metoda Lean Analytics",
    author: "Alistair Croll, Benjamin Yoskovitz",
    rating: 4.1,
    reviewCount: 47,
    readTime: 54,
    category: "Przedsiębiorczość i start-up",
    categories: ["Przedsiębiorczość i start-up"],
    hasAudio: true,
    isFree: false,
    slug: "metoda-lean-analytics",
    cover: "/covers/books/Metoda Lean Analytics.png",
  },
  {
    id: 133,
    title: "Superfari",
    author: "Pat Flynn",
    rating: 4.5,
    reviewCount: 39,
    readTime: 29,
    category: "Marketing",
    categories: ["Marketing"],
    hasAudio: true,
    isFree: false,
    slug: "superfari",
    cover: "/covers/books/Superfani.png",
  },
  {
    id: 134,
    title: "Głowa do liczb",
    author: "Barbara Oakley",
    rating: 4.6,
    reviewCount: 41,
    readTime: 28,
    category: "Produktywność i efektywność",
    categories: ["Produktywność i efektywność"],
    hasAudio: true,
    isFree: false,
    slug: "glowa-do-liczb",
    cover: "/covers/books/Głowa do liczb.png",
  },
  {
    id: 135,
    title: "Twórcza kradzież",
    author: "Austin Kleon",
    rating: 4.71,
    reviewCount: 36,
    readTime: 25,
    category: "Kariera i sukces",
    categories: ["Kariera i sukces"],
    hasAudio: true,
    isFree: false,
    slug: "tworcza-kradziez",
    cover: "/covers/books/Twórcza kradzież.png",
  },
  {
    id: 136,
    title: "Wojna sztuki",
    author: "Steven Pressfield",
    rating: 4.4,
    reviewCount: 37,
    readTime: 26,
    category: "Kariera i sukces",
    categories: ["Kariera i sukces"],
    hasAudio: true,
    isFree: false,
    slug: "wojna-sztuki",
    cover: "/covers/books/Wojna sztuki.png",
  },
  {
    id: 137,
    title: "Dopaminowy detoks",
    author: "Thibaut Meurisse",
    rating: 3.9,
    reviewCount: 38,
    readTime: 16,
    category: "Produktywność i efektywność",
    categories: ["Produktywność i efektywność", "Zdrowie"],
    hasAudio: true,
    isFree: false,
    slug: "dopaminowy-detoks",
    cover: "/covers/books/Dopaminowy detoks.png",
  },
  {
    id: 138,
    title: "Mit charyzmy",
    author: "Olivia Fox Cabane",
    rating: 4.2,
    reviewCount: 43,
    readTime: 31,
    category: "Komunikacja i relacje",
    categories: ["Komunikacja i relacje"],
    hasAudio: true,
    isFree: false,
    slug: "mit-charyzmy",
    cover: "/covers/books/Mit charyzmy.png",
  },
  {
    id: 139,
    title: "Gotowi na start",
    author: "Pat Flynn",
    rating: 4.6,
    reviewCount: 56,
    readTime: 23,
    category: "Przedsiębiorczość i start-up",
    categories: ["Przedsiębiorczość i start-up"],
    hasAudio: true,
    isFree: false,
    slug: "gotowi-na-start",
    cover: "/covers/books/Gotowi na start.png",
  },
  {
    id: 140,
    title: "Samograj",
    author: "Mike Michalowicz",
    rating: 4.3,
    reviewCount: 45,
    readTime: 31,
    category: "Przedsiębiorczość i start-up",
    categories: ["Przedsiębiorczość i start-up"],
    hasAudio: true,
    isFree: false,
    slug: "samograj",
    cover: "/covers/books/Samograj.png",
  },
  {
    id: 141,
    title: "Glukozowa rewolucja",
    author: "Jessie Inchauspé",
    rating: 4.8,
    reviewCount: 42,
    readTime: 31,
    category: "Zdrowie",
    categories: ["Zdrowie"],
    hasAudio: true,
    isFree: false,
    slug: "glukozowa-rewolucja",
    cover: "/covers/books/Glukozowa rewolucja.png",
  },
  {
    id: 142,
    title: "Śmierć z zerem na koncie",
    author: "Bill Perkins",
    rating: 4.1,
    reviewCount: 49,
    readTime: 21,
    category: "Pieniądze i wolność finansowa",
    categories: ["Pieniądze i wolność finansowa"],
    hasAudio: true,
    isFree: false,
    slug: "smierc-z-zerem-na-koncie",
    cover: "/covers/books/Śmierć z zerem na koncie.png",
  },
  {
    id: 143,
    title: "Nie tłumacz się, działaj",
    author: "Brian Tracy",
    rating: 4.03,
    reviewCount: 38,
    readTime: 34,
    category: "Produktywność i efektywność",
    categories: ["Produktywność i efektywność"],
    hasAudio: true,
    isFree: false,
    slug: "nie-tlumacz-sie-dzialaj",
    cover: "/covers/books/Nie tłumacz się, działaj.png",
  },
  {
    id: 144,
    title: "Na własne ryzyko",
    author: "Nassim Nicholas Taleb",
    rating: 4.4,
    reviewCount: 45,
    readTime: 30,
    category: "Psychologia",
    categories: ["Psychologia"],
    hasAudio: true,
    isFree: false,
    slug: "na-wlasne-ryzyko",
    cover: "/covers/books/Na własne ryzyko.png",
  },
  {
    id: 145,
    title: "Siła stresu",
    author: "Kelly McGonigal",
    rating: 4.3,
    reviewCount: 46,
    readTime: 33,
    category: "Rozwój osobisty",
    categories: ["Rozwój osobisty"],
    hasAudio: true,
    isFree: false,
    slug: "sila-stresu",
    cover: "/covers/books/Siła stresu.png",
  },
  {
    id: 146,
    title: "Spowiedź nagłowowego przedsiębiorcy",
    author: "Artur Racicki",
    rating: 4.6,
    reviewCount: 51,
    readTime: 46,
    category: "Biznes i przywództwo",
    categories: ["Biznes i przywództwo"],
    hasAudio: true,
    isFree: false,
    slug: "spowiedz-naglowowego-przedsiebiorcy",
    cover: "/covers/books/Spowiedź nałogowego przedsiębiorcy.png",
  },
  {
    id: 147,
    title: "Sięgaj jak najdalej",
    author: "David Epstein",
    rating: 4.7,
    reviewCount: 38,
    readTime: 34,
    category: "Rozwój osobisty",
    categories: ["Rozwój osobisty"],
    hasAudio: true,
    isFree: false,
    slug: "siegaj-jak-najdalej",
    cover: "/covers/books/Sięgaj jak najdalej.png",
  },
  {
    id: 148,
    title: "Szum",
    author: "Daniel Kahneman, Cass Sunstein",
    rating: 4.5,
    reviewCount: 38,
    readTime: 47,
    category: "Psychologia",
    categories: ["Psychologia"],
    hasAudio: true,
    isFree: false,
    slug: "szum",
    cover: "/covers/books/Szum.png",
  },
  {
    id: 149,
    title: "Przewaga szczęścia",
    author: "Shawn Achor",
    rating: 4.4,
    reviewCount: 36,
    readTime: 31,
    category: "Rozwój osobisty",
    categories: ["Rozwój osobisty"],
    hasAudio: true,
    isFree: false,
    slug: "przewaga-szczescia",
    cover: "/covers/books/Przewaga szczęścia.png",
  },
];

export const freeBooks = allBooks.filter(b => b.isFree);

export const recentBooks = [...allBooks].reverse().slice(0, 12);

export const howItWorks = [
  {
    step: 1,
    title: "Wybieramy najlepsze książki",
    description: "Selekcjonujemy tysiące tytułów i wybieramy tylko te, które naprawdę warto przeczytać.",
    icon: "📚",
  },
  {
    step: 2,
    title: "Transformujemy teorię w praktykę",
    description: "Przekształcamy wiedzę w konkretne, actionable insights gotowe do zastosowania od razu.",
    icon: "⚙️",
  },
  {
    step: 3,
    title: "Dodajemy komentarz autorski",
    description: "Każda analiza zawiera nasz unikalny komentarz, który nadaje kontekst i perspektywę.",
    icon: "✍️",
  },
  {
    step: 4,
    title: "Dostarczamy w wielu formatach",
    description: "Tekst PDF, wersja audio, infografiki i zadania wdrożeniowe — wybierz swój styl nauki.",
    icon: "🎯",
  },
];

export const whyLumeo = [
  {
    title: "Esencja w 30 minut",
    description: "Zamiast czytać 300 stron, w 30 minut poznajesz kluczowe idee i możesz działać.",
    icon: "⏱️",
  },
  {
    title: "Unikalny komentarz",
    description: "Nie streszczamy — analizujemy. Każda analiza zawiera nasz autorski komentarz i perspektywę.",
    icon: "💡",
  },
  {
    title: "Infografiki",
    description: "Wizualne podsumowania najważniejszych koncepcji, które łatwo zapamiętasz i zachowasz.",
    icon: "🎨",
  },
  {
    title: "Wersje audio",
    description: "Słuchaj analiz podczas jazdy samochodem, biegania lub przerwy w pracy.",
    icon: "🎧",
  },
  {
    title: "Zadania wdrożeniowe",
    description: "Każda analiza kończy się konkretnymi zadaniami, które pomagają zastosować wiedzę w życiu.",
    icon: "✅",
  },
  {
    title: "Lumeo Lab",
    description: "Społeczność, która współtworzy platformę. Twój głos ma wpływ na to, co czytamy następne.",
    icon: "🔬",
  },
];

export const reviews = [
  {
    name: "Jacek P.",
    text: "Lumeo to oszczędność czasu i jakość w jednym. Zamiast czytać książkę przez tydzień, w 30 minut mam to, czego potrzebuję do działania.",
    avatar: "JP",
  },
  {
    name: "Przemysław K.",
    text: "Próbowałem Blinkist, ale Lumeo jest po prostu lepsze. Analizy są głębsze, komentarz autorski daje dodatkowy kontekst, a wersja polska to ogromny plus.",
    avatar: "PK",
  },
  {
    name: "Daria M.",
    text: "Format jest idealny — czytam podczas kawy, słucham audio w drodze do pracy. Zadania wdrożeniowe naprawdę pomagają zastosować wiedzę.",
    avatar: "DM",
  },
  {
    name: "David P.",
    text: "Kupiłem subskrypcję roczną i to jedna z najlepszych decyzji tego roku. Każdy tydzień nowa analiza, każda warta swojej ceny.",
    avatar: "DP",
  },
  {
    name: "Krystian H.",
    text: "Infografiki są genialne. Wieszam je w biurze i codziennie przypominają mi kluczowe zasady z przeczytanych analiz.",
    avatar: "KH",
  },
  {
    name: "Anna Z.",
    text: "Polecam każdemu, kto chce się rozwijać, ale nie ma czasu na czytanie całych książek. Jakość analiz jest naprawdę wysoka.",
    avatar: "AZ",
  },
];

export const blogPosts = [
  { title: "Tragedia wspólnych pastwisk", slug: "tragedia-wspolnych-pastwisk", date: "15 sty 2026", category: "Psychologia", image: "/covers/40.png", excerpt: "Dlaczego racjonalne działanie jednostek prowadzi do katastrofy dla całej grupy? To jedno z najważniejszych odkryć w psychologii społecznej." },
  { title: "Nomofobia — uzależnienie od telefonu", slug: "nomofobia", date: "10 sty 2026", category: "Psychologia", image: "/covers/48.png", excerpt: "Strach przed rozstaniem z telefonem dotyka już ponad 70% dorosłych. Sprawdź, jak to wpływa na Twoją produktywność i relacje." },
  { title: "Paradoks Abilene", slug: "paradoks-abilene", date: "5 sty 2026", category: "Biznes i przywództwo", image: "/covers/46.png", excerpt: "Grupa ludzi podejmuje decyzję, której nikt tak naprawdę nie chciał. Jak ten mechanizm sabotuje Twój zespół i jak go uniknąć?" },
  { title: "Prawo Galla", slug: "prawo-galla", date: "2 sty 2026", category: "Przedsiębiorczość", image: "/covers/44.png", excerpt: "Każdy działający złożony system wyewoluował z prostszego systemu, który działał. Co to oznacza dla Twojego biznesu?" },
  { title: "Ikigai — sens życia po japońsku", slug: "ikigai", date: "28 gru 2025", category: "Rozwój osobisty", image: "/covers/13.png", excerpt: "Japończycy z Okinawy żyją najdłużej na świecie. Ich sekret kryje się w jednym słowie, które łączy pasję, misję i powołanie." },
  { title: "Cykl zadłużenia Dalio", slug: "cykl-zadluzenia", date: "22 gru 2025", category: "Finanse", image: "/covers/9.png", excerpt: "Ray Dalio przez dekady badał wzorce gospodarcze. Jego model cyklu długu pomaga przewidzieć kryzysy, zanim nadejdą." },
  { title: "Prawo Goodharta", slug: "prawo-goodharta", date: "18 gru 2025", category: "Biznes i przywództwo", image: "/covers/52.png", excerpt: "Kiedy miara staje się celem, przestaje być dobrą miarą. Dlaczego KPI mogą niszczyć firmy i jak ustalać właściwe cele?" },
  { title: "Dlaczego Rockefeller był tak bogaty?", slug: "rockefeller", date: "14 gru 2025", category: "Finanse", image: "/covers/8.png", excerpt: "Nie chodziło tylko o ropę naftową. Rockefeller stosował zasady, które do dziś są podstawą budowania trwałego majątku." },
];

export const faqItems = [
  {
    question: "Jak często pojawiają się nowe analizy?",
    answer: "Nowe analizy dodajemy regularnie — co najmniej 2-4 nowe tytuły miesięcznie. Możesz śledzić nowości w sekcji 'Ostatnio dodane' lub zapisać się na newsletter.",
  },
  {
    question: "Czy wszystkie analizy mają wersje audio?",
    answer: "Większość analiz posiada wersje audio. Przy każdej analizie bez audio aktywnie pracujemy nad nagraniem. Przy opisie każdej książki widnieje ikona słuchawek, jeśli audio jest dostępne.",
  },
  {
    question: "Czy subskrypcja odnawia się automatycznie?",
    answer: "Tak, subskrypcja odnawia się automatycznie po upływie okresu rozliczeniowego. Możesz ją anulować w dowolnym momencie z poziomu swojego konta — bez żadnych konsekwencji.",
  },
  {
    question: "Czy potrzebuję karty kredytowej do okresu próbnego?",
    answer: "Tak, przy rejestracji prosimy o dane karty, ale przez 7 dni próbnych nie pobieramy żadnych opłat. Jeśli anulujesz przed końcem trialu, nie zostaniesz obciążony.",
  },
  {
    question: "Czy Lumeo narusza prawa autorskie?",
    answer: "Nie. Lumeo dostarcza oryginalne analizy, komentarze i syntezy — nie reprodukujemy treści książek. Nasze analizy uzupełniają oryginalne dzieła i zachęcają do zakupu pełnych wydań.",
  },
  {
    question: "Czy mogę otrzymać fakturę VAT?",
    answer: "Tak, wystawiamy faktury VAT. Podczas rejestracji lub w ustawieniach konta możesz podać dane firmowe i otrzymasz fakturę na każdą płatność.",
  },
  {
    question: "Czym Lumeo różni się od Blinkist?",
    answer: "Lumeo to platforma w języku polskim z autorskim komentarzem, infografikami i zadaniami wdrożeniowymi. Nie tylko streszczamy — analizujemy i pomagamy wdrożyć wiedzę w życie. Dodatkowo jako subskrybent masz wpływ na rozwój platformy przez Lumeo Lab.",
  },
];

export const partners = [
  "Dawid Haracz",
  "Studio Emka",
  "Czarna Owca",
  "PWN",
  "Galaktyka",
  "Freedom Publishing",
  "Znak",
  "Agora",
  "MT Biznes",
];

export const stats = [
  { value: "149", label: "przeanalizowanych książek" },
  { value: "74h", label: "zaoszczędzonych na notatkach" },
  { value: "2520", label: "autorskich komentarzy" },
];
